@baseUrl = http://localhost:5000/api/v1


GET {{baseUrl}}/expense-tracker/transaction

###


POST {{baseUrl}}/expense-tracker/transaction
Content-Type: application/json

{
  "name": "Salary",
  "type": "Investment",
  "amount": 300
}

###


DELETE {{baseUrl}}/expense-tracker/transaction
Content-Type: application/json

{
  "_id": "630c7f4bcfb053af6f9a581d"
}


###

GET {{baseUrl}}/expense-tracker/labels




###


POST {{baseUrl}}/expense-tracker/categories
Content-Type: application/json

{
  "type": "Savings",
  "color": "#36A2EB"
}